app/posts/blueprint.py
from flask import Blueprint, render_template, request

from models.db_inter import Post
from app import db

posts = Blueprint('posts', __name__,  template_folder='templates')


@posts.route('/')
def index():
	postss = Post.query.all()
	return render_template('posts/index.html', n="blogger", posts=postss)

@posts.route('/newpost')
def newpost():
	return render_template('posts/newpost.html', n="poster")

@posts.route('/newpost/send', methods=["POST"])
def send():
	if len(request.form["text"]) == 0:
		return "Type something in text at least", 200
	np = Post(text=request.form["text"], title=request.form["title"])
	db.session.add(np)
	db.session.commit()
	return "ok", 200

@posts.route('/<slug>')
def viewpost(slug):
	post = Post.query.filter(Post.slug==slug).first()
	return render_template('posts/postview.html', post=post, n="reader")

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block header %}
	All posts
{% endblock %}

{% block text %}
{% for post in posts %}
	<div class="post">
		<h4><a href="/blog/{{ post.slug }}">{{ post.title }}</a></h4>
	</div>
{% endfor %}
{% endblock %}

{% block additional %}
	<input type="button" value="New post" onclick="window.location.href='{{ url_for('posts.newpost') }}';" >
{% endblock %}

app/posts/templates/posts/newpost.html
{% extends 'base.html' %}

{% block header %}
	New post
{% endblock %}

{% block text %}
	Fill forms below to publish new post!
{% endblock %}

{% block additional %}
<div class="postform">
	<form action="{{ url_for('posts.send')}}" method="post">
		<input type="text" name="title" size="40" placeholder="Title (optional)">
		<textarea name="text" rows="8" cols="80" class="textfield" placeholder="Your text..."></textarea>
		<div class="sendbox">
			<img src="{{ url_for('static', filename='pic/captcha.png') }}" alt="Stupid captcha" class="capthca">
			<input type="text" size="40" placeholder="Captcha">
			<input type="submit" value="Send!">
		</div>
	</form>
 </div>

 {% endblock %}

app/posts/templates/posts/postview.html
{% extends 'base.html' %}

{% block header %}
	{{ post.title }}
{% endblock %}

{% block text %}
	{{ post.text }}
{% endblock %}

{% block additional %}
	<p>Author: {{ post.author }}</p>
	<p>Created: {{ post.created }}</p>
{% endblock %}