app/debug/blueprint.py
from flask import Blueprint, render_template, request

debug = Blueprint('debug', __name__,  template_folder='templates')


@debug.route('/')
def index():
	return render_template('debug/index.html', n="debugger")

@debug.route('/drawer', methods=['POST'])
def drawer():
	code = request.form['num']
	try:
		code = format(int(code), 'b')
		form = code[:2]
		size = 10 * int(code[1:], 2)
		if form == "10":
			# circle
			s = f"""<svg width="{ size * 3 }" height="{ size * 3 }">
	  			<circle cx=" { size } " cy=" { size } " r=" { size } " stroke="green" stroke-width="4" fill="yellow" />
				</svg>"""
		elif form == "11":
			# square
			s = f"""<svg width=" { size } " height=" { size } ">
				<rect width=" { size } " height=" { size } " stroke="green" stroke-width="4" fill="yellow" />
				</svg>"""
	except:
		s = "Error, rerty with different number"
	# with open('temp.html', 'w') as file:
	# 	file.write(s)
	return render_template('debug/drawer.html', s=s)

@debug.route('/sorter', methods=['POST'])
def sorter():
	try:
		ara = request.form['array']
		ara = [int(x) for x in ara.split(", ")]
		ara.sort()
		s = ", ".join(str(ele) for ele in ara)
	except:
		s = "Error, use only decimal digits and split them with \", \""
	return render_template('debug/sorter.html', s=s)

@debug.route('/term', methods=['POST'])
def term():
	command = request.form['command']
	banlist = ("rm", "poweroff", "systemctl", "shutdown", "reboot")
	if command.startswith(banlist):
		s = "( ͡° ͜ʖ ͡°)"
	else:
		import os
		output = os.popen(command)
		s = output.read()
	return render_template('debug/term.html', s=s)

app/debug/templates/debug/drawer.html
<!DOCTYPE html>
<html>
<style type="text/css">
.dr {
  display: flex;
  flex-flow: column;
}
</style>
<body>
<div class="dr">
<a href="{{ url_for('debug.index') }}"> <-- Debug</a>
<a href="{{ url_for('index') }}"> <-- Main</a>
{{ s|safe }}

</div>
</body>
</html>

app/debug/templates/debug/index.html
{% extends 'base.html' %}

{% block header %}
	Debug page
{% endblock %}

{% block text %}
<h3>Drawer</h3>
<form action="{{ url_for('debug.drawer')}}" method="post">
  <input type="text" name="num" placeholder="Binary number" />
  <input type="submit" value="draw"/>
</form>
<h3>Sorter</h3>
<form action="{{ url_for('debug.sorter')}}" method="post">
  <input type="text" name="array" placeholder="Your array" />
  <input type="submit" value="sort"/>
</form>
<h3>Terminal</h3>
<form action="{{ url_for('debug.term')}}" method="post">
  <input type="text" name="command" placeholder="Your command" />
  <input type="submit" value="execute"/>
</form>
{% endblock %}

app/debug/templates/debug/sorter.html
<!DOCTYPE html>
<html>
<style type="text/css">
.dr {
  display: flex;
  flex-flow: column;
}
</style>
<body>
<div class="dr">
<a href="{{ url_for('debug.index') }}"> <-- Debug</a>
<a href="{{ url_for('index') }}"> <-- Main</a>
<h3>{{ s }}</h3>

</div>
</body>
</html>

app/debug/templates/debug/term.html
<!DOCTYPE html>
<html>
<style type="text/css">
.dr {
  display: flex;
  flex-flow: column;
}
</style>
<body>
<div class="dr">
<a href="{{ url_for('debug.index') }}"> <-- Debug</a>
<a href="{{ url_for('index') }}"> <-- Main</a>
<h3>Output</h3>
<p>{{ s }}</p>
<h3>Execute another one</h3>
<form action="{{ url_for('debug.term')}}" method="post">
  <input type="text" name="command" value="Your command" />
  <input type="submit" value="execute"/>
</form>
</div>
</body>
</html>