app/models/db_inter.py
from app import db
from datetime import datetime
import re


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author = db.Column(db.String(30))
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    text = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        if self.title is None:
            self.title = self.text.split(".")[0]
        self.slug = self.genslug(self.title)
        if self.author is None:
            self.author = "Anonymous"


    def genslug(self, s):
        pattern = r'[^\w+]'
        return re.sub(pattern, '-', s)

    def __repr__(self):
        return "<Post: {}, title: {}>".format(self.id, self.title)

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
# from db_inter import db

# postdb = db("postdb")



app = Flask(__name__)
app.config.from_object(Configuration)


db = SQLAlchemy(app)



import view

from posts.blueprint import posts
app.register_blueprint(posts, url_prefix='/blog')
from debug.blueprint import debug
app.register_blueprint(debug, url_prefix='/debug')


if __name__ == 'main':
	app.run(debug=True)

app/debug/blueprint.py
from flask import Blueprint, render_template, request

debug = Blueprint('debug', __name__,  template_folder='templates')


@debug.route('/')
def index():
	return render_template('debug/index.html', n="debugger")

@debug.route('/drawer', methods=['POST'])
def drawer():
	code = request.form['num']
	try:
		code = format(int(code), 'b')
		form = code[:2]
		size = 10 * int(code[1:], 2)
		if form == "10":
			# circle
			s = f"""<svg width="{ size * 3 }" height="{ size * 3 }">
	  			<circle cx=" { size } " cy=" { size } " r=" { size } " stroke="green" stroke-width="4" fill="yellow" />
				</svg>"""
		elif form == "11":
			# square
			s = f"""<svg width=" { size } " height=" { size } ">
				<rect width=" { size } " height=" { size } " stroke="green" stroke-width="4" fill="yellow" />
				</svg>"""
	except:
		s = "Error, rerty with different number"
	# with open('temp.html', 'w') as file:
	# 	file.write(s)
	return render_template('debug/drawer.html', s=s)

@debug.route('/sorter', methods=['POST'])
def sorter():
	try:
		ara = request.form['array']
		ara = [int(x) for x in ara.split(", ")]
		ara.sort()
		s = ", ".join(str(ele) for ele in ara)
	except:
		s = "Error, use only decimal digits and split them with \", \""
	return render_template('debug/sorter.html', s=s)

@debug.route('/term', methods=['POST'])
def term():
	command = request.form['command']
	banlist = ("rm", "poweroff", "systemctl", "shutdown", "reboot")
	if command.startswith(banlist):
		s = "( ͡° ͜ʖ ͡°)"
	else:
		import os
		output = os.popen(command)
		s = output.read()
	return render_template('debug/term.html', s=s)

app/main.py
from app import app
import view

if __name__ == 'main':
	app.run(debug=True)

app/posts/blueprint.py
from flask import Blueprint, render_template, request

from models.db_inter import Post
from app import db

posts = Blueprint('posts', __name__,  template_folder='templates')


@posts.route('/')
def index():
	postss = Post.query.all()
	return render_template('posts/index.html', n="blogger", posts=postss)

@posts.route('/newpost')
def newpost():
	return render_template('posts/newpost.html', n="poster")

@posts.route('/newpost/send', methods=["POST"])
def send():
	if len(request.form["text"]) == 0:
		return "Type something in text at least", 200
	np = Post(text=request.form["text"], title=request.form["title"])
	db.session.add(np)
	db.session.commit()
	return "ok", 200

@posts.route('/<slug>')
def viewpost(slug):
	post = Post.query.filter(Post.slug==slug).first()
	return render_template('posts/postview.html', post=post, n="reader")

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Document</title>
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='master.css') }}" />
</head>
<body>
	<div class="main">
		<div class="hero">
			<h2>Hello {{ n }}</h2>
			<li class="menu-list">
			<ul><a href="{{ url_for('index') }}">GOTO: Main</a></ul>
			<ul><a href="{{ url_for('posts.index') }}">GOTO: Blog</a></ul>
			<ul><a href="{{ url_for('info') }}">GOTO: Info</a></ul>
			<ul><a href="{{ url_for('debug.index') }}">GOTO: Debug</a></ul>
			</li>
		</div>

	</div>
	<div class="contents">
		<h1>
			{% block header %}

			{% endblock %}
		</h1>
		<p>
			{% block text %}

			{% endblock %}
		</p>
		<div class="additional">
			{% block additional %}

			{% endblock %}
	</div>
</body>
<footer>
	<div class="footer-items">
		<p>Test project by akd</p>

</footer>
</html>

app/templates/debug.html
{% extends 'base.html' %}

{% block header %}
	Debug page
{% endblock %}

{% block additional %}

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block header %}
	HOWDY!
{% endblock %}

{% block text %}
	This is a main page!
{% endblock %}

app/templates/info.html
{% extends 'base.html' %}

{% block header %}
	Info page
{% endblock %}

{% block text %}
	This is a test project. It does nothing, netherless it should do. Be patient, and some day this would become something insane!
{% endblock %}